name: test
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
      with:
        skip_adding_nixpkgs_channel: true
    - uses: cachix/cachix-action@v6
      with:
        name: zxcvbn-hs
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-shell --run 'cabal build && cabal test'
